name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: storybook-deploy
  cancel-in-progress: true

jobs:
  # Build and Deploy Storybook
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # 3. Install Dependencies
      - name: Install dependencies
        run: npm install

      # 4. Cache build artifacts
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: dist/ # Cache everything built into dist
          key: ${{ runner.os }}-fds-design-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-fds-design-

      # 5. Build Storybook (includes theme build)
      - name: Build Storybook
        run: npm run build-storybook

      # 6. Upload Storybook artifacts for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: storybook-static

  # Deploy to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      # 7. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
